SIP minutes: 2019 November
dwijnand/docs.scala-lang pull request #1
Opened 2019-12-09 17:06 UTC by dwijnand

2019-12-09 19:13 UTC, SethTisue reviewed
LGTM, I made only very minor comments

and, one suggestion: could this say something about when the next meeting/meetings/retreats are expected to occur?

2019-12-09 19:13 UTC, SethTisue commented on _sips/minutes/2019-11-27-sip-minutes.md
> +* Guillaume Marters ([@smarter](https://github.com/smarter), EPFL
s/Marters/Martres/

2019-12-09 19:13 UTC, SethTisue commented on _sips/minutes/2019-11-27-sip-minutes.md
> +for Scala 3.  Those individual proposal still need to be individually reviewed, but doing so will take time.
s/proposal/proposals/

2019-12-09 19:13 UTC, SethTisue commented on _sips/minutes/2019-11-27-sip-minutes.md
> +initialise a feature freeze.  What that means is that new things won't be added, instead existing changes will
s/initialise/initiate/

2019-12-09 19:13 UTC, SethTisue commented on _sips/minutes/2019-11-27-sip-minutes.md
> +their expectations that its very unlikely they'll be able to target Scala 3.0.
maybe add "and would have to wait for some future 3.x release"

2019-12-10 09:30 UTC, darjutak commented on _sips/minutes/2019-11-27-sip-minutes.md
> +A month ago a thread was created on the Contributors forum announcing that the next Dotty release will
```suggestion
A month ago a thread was created on the [Contributors forum announcing that the next Dotty release](https://contributors.scala-lang.org/t/preparing-for-feature-freeze) will
```

2019-12-10 09:40 UTC, darjutak commented on _sips/minutes/2019-11-27-sip-minutes.md
> +The next meeting will be in December, but also the Committee intends to have another retreat in March 2020.
```suggestion
The next meeting will be in December 18th at 5 PM CET, but also the Committee intends to have another retreat in March 2020.
```

2019-12-10 09:41 UTC, darjutak requested changes
Looks excellent to me, thank you! (just a couple of minor additions)

2019-12-10 16:45 UTC, sjrd approved these changes

2019-12-10 17:18 UTC, dwijnand commented
Thanks, I'll PR it now.

2019-12-10 17:18 UTC, closed without merging